const HTTP_STATUS_CODE = {
  100: '100 Continue - 클라이언트가 서버로 보낸 요청에 문제가 없으니 다음 요청을 이어서 보내도 된다는 것을 의미',
  101: '101 Switching Protocols - 클라이언트가 Upgrade (en-US) 헤더를 통해 요청한 것에 따라 서버가 프로토콜을 바꾼다는 것을 알려주는 응답 코드',
  103: '103 Early Hints - 서버가 응답을 준비하는 동안에도 사용자 에이전트가 자원을 미리 읽어들일 수 있도록, 주로 Link (en-US) 헤더와 함께 사용',
  200: '200 OK - 요청이 성공했음을 나타내는 성공 응답 상태 코드',
  201: '201 Created - 요청이 성공적으로 처리되었으며, 자원이 생성되었음을 나타내는 성공 상태 응답 코드',
  202: '202 Accepted - 요청이 성공적으로 접수되었으나, 아직 해당 요청에 대해 처리 중이거나 처리 시작 전임을 의미',
  203: '203 Non-Authoritative Information - 요청이 성공했지만 포함된 페이로드가 원본 서버의 200 OK 응답에서 변환 proxy에 의해 수정되었음을 나타냅니다',
  204: '204 No Content - 요청이 성공했으나 클라이언트가 현재 페이지에서 벗어나지 않아도 된다는 것을 나타냅니다.',
  205: '205 Reset Content - form의 내용을 지우거나 캔버스 상태를 재설정하거나 UI를 새로 고치려면 client의 문서뷰를 새로고침하라고 알려준다.',
  206: '206 Partial Content - Range 헤더에 기술된 데이터 범위에 대한 요청이 성공적으로 응답되어 바디에 해당되는 데이터를 담고 있다는 것을 알려줍니다.',
  300: '300 Multiple Choices - 요청에 두 개 이상의 가능한 응답이 있음을 나타냅니다.',
  301: '301 Moved Permanently - 요청한 리소스가 Location (en-US) 헤더에 주어진 URL로 완전히 옮겨졌다는 것을 나타낸다.',
  302: '302 Found - 클라이언트가 요청한 리소스가 Location (en-US) 헤더에 주어진 URL에 일시적으로 이동되었음을 가리킨다.',
  303: '303 See Other - 리디렉션이 새로 업로드된 리소스가 아니라 다른 페이지 (예 : 확인 페이지 또는 업로드 진행률 페이지)에 연결됨을 나타냅니다.',
  304: '304 Not Modified - 요청된 리소스를 재전송할 필요가 없음을 나타낸다.',
  307: '307 Temporary Redirect - 요청한 리소스가 Location (en-US) 헤더에 주어진 URL 로 임시로 옮겨졌다는 것을 나타냅니다.',
  308: '308 Permanent Redirect - 요청된 리소스가 Location 헤더에서 제공한 URL로 확실히 이동되었음을 나타냅니다.',
  400: '400 Bad Request - 서버가 클라이언트 오류(예: 잘못된 요청 구문, 유효하지 않은 요청 메시지 프레이밍, 또는 변조된 요청 라우팅)를 감지해 요청을 처리할 수 없거나, 하지 않는다는 것을 의미합니다',
  401: '401 Unauthorized - 해당 리소스에 유효한 인증 자격 증명이 없기 때문에 요청이 적용되지 않았음을 나타냅니다.',
  402: '402 Payment Required - 향후 사용을 위해 예약된 비표준 클라이언트 오류 상태 응답 코드입니다.',
  403: '403 Forbidden - 서버에 요청이 전달되었지만, 권한 때문에 거절되었다는 것을 의미',
  404: '404 Not Found - 서버가 요청받은 리소스를 찾을 수 없다는 것을 의미',
  405: '405 Method Not Allowed - 요청 방법이 서버에 의해 알려졌으나, 사용 불가능한 상태임을 가리킵니다.',
  406: '406 Not Acceptable - 서버가 요청의 사전 content negotiation 헤더에 정의 된 허용 가능한 값 목록과 일치하는 응답을 생성할 수 없으며 서버가 기본 표현을 제공하지 않음을 나타냅니다.',
  407: '407 Proxy Authentication Required - 요청된 리소스에 액세스 할 수 있는 서버와 브라우저 사이에 있는 프록시 서버에 대한 유효한 인증 자격 증명이 없기 때문에 요청이 적용되지 않았음을 나타냅니다.',
  408: '408 Request Timeout - 서버가 사용하지 않는 연결을 끊고 싶다는 것을 의미',
  409: '409 Conflict - 서버의 현재 상태와 요청이 충돌했음을 나타낸다.',
  410: '410 Gone - 원본 서버에서 대상 리소스에 대한 액세스를 더 이상 사용할 수 없으며 이 조건이 영구적일 가능성이 있음을 나타냅니다.',
  411: '411 Length Required - 서버가 정의된 Content-Length 헤더없이 요청을 수락하지 않음을 나타낸다.',
  412: '412 Precondition Failed - 대상 리소스에 대한 액세스가 거부되었음을 나타냅니다.',
  413: '413 Payload Too Large - 요청 엔티티가 서버에 의해 정의된 제한보다 크다는 것을 나타낸다.',
  414: '414 URI Too Long - 클라이언트가 요청한 URI가 서버가 해석하려는 것보다 길다는 것을 나타냅니다.',
  415: '415 Unsupported Media Type - 페이로드 형식이 지원되지 않는 형식이기 때문에 서버가 요청 수락을 거부함을 나타냅니다.',
  416: '416 Range Not Satisfiable - 서버가 요청받은 범위에 대해서 서비스 할 수 없음을 알려줍니다.',
  417: '417 Expectation Failed - 요청의 Expect 헤더에 제공된 예상을 충족 할 수 없음을 나타냅니다 .',
  418: '418 Im a teapot - 서버가 찻 주전자이기 때문에 커피 내리기를 거절했다는 것을 의미합니다. ',
  422: '422 Unprocessable Entity - 서버가 요청을 이해하고 요청 문법도 올바르지만 요청된 지시를 따를 수 없음을 나타냅니다.',
  425: '425 Too Early - 서버가 재생 될 수있는 요청을 처리 할 위험이 없음을 나타내며, 이로 인해 재생 공격의 가능성이 있습니다.',
  426: '426 Upgrade Required - 서버가 현재 프로토콜을 사용하여 요청을 수행하는 것을 거부하지만 클라이언트가 다른 프로토콜로 업그레이드 한 후에 수행 할 수 있음을 나타냅니다.',
  428: '428 Precondition Required - 서버에 조건부 요청이 필요함을 나타냅니다.',
  429: '429 Too Many Requests - 사용자가 주어진 시간동안 너무 많은 요청을 보냈음을 나타냅니다',
  431: '431 Request Header Fields Too Large - HTTP 헤더의 크기가 너무 크기 때문에 처리가 불가능함을 알려준다.',
  451: '451 Unavailable For Legal Reasons - 사용자가 법적 조치가 발행된 웹 페이지와 같은 법적 이유로 사용할 수 없는 리소스를 요청했음을 나타냅니다.',
  500: '500 Internal Server Error - 요청을 처리하는 과정에서 서버가 예상하지 못한 상황에 놓였다는 것을 나타냅니다.',
  501: '501 Not Implemented - 요청을 수행할 수 있는 기능을 서버가 지원하지 않는다는 것을 의미합니다.',
  502: '502 Bad Gateway - 서버가 게이트웨이나 프록시 서버 역할을 하면서 업스트림 서버로부터 유효하지 않은 응답을 받았다는 것을 가르킨다.',
  503: '503 Service Unavailable - 서버가 요청(request)을 처리할 준비가 되지 않은 것을 나타낸다.',
  504: '504 Gateway Timeout - 서버가 게이트웨이(gateway) 혹은 프록시(proxy)의 역할을 하는 동안 시간 안에 업스트림 서버(upstream server)로부터 요청을 마치기 위해 필요한 응답를 받지 못 했음을 나타냅니다.',
  505: '505 HTTP Version Not Supported - 요청에 사용된 HTTP 버전이 서버가 지원하지 않음을 알립니다.',
  506: '506 Variant Also Negotiates - Transparent Content Negotiation의 컨텍스트에서 제공될 수 있습니다 ',
  507: '507 Insufficient Storage - WebDAV(Web Distributed Authoring and Versioning) 프로토콜의 컨텍스트에서 제공될 수 있습니다',
  508: '508 Loop Detected -  WebDAV(Web Distributed Authoring and Versioning) 프로토콜의 컨텍스트에서 제공될 수 있습니다.',
  510: '510 Not Extended - RFC 2774에 정의된 HTTP 확장 프레임워크의 컨텍스트에서 전송됩니다.',
  511: '511 Network Authentication Required - 클라이언트가 네트워크 액세스를 얻기 위해 인증해야 함을 나타냅니다.',
};
